### ISSUE TITLE
kukui_bookworm_image root password 

### ISSUE THREAD

**Issue by riacht** [hexdump0815/linux-mainline-mediatek-mt81xx-kernel#13]
Hi, booting from usb OK,
but can't login
root 
changeme
Appritiate your help.

**Comment by hexdump0815** [comment]
the images come without a root password set - you'll have to login as user "linux", sudo to root and then set a password for root if root login is required

**Comment by riacht** [comment]
Exactely,linux,
I came to that s.wat later,
but nevertheless,thank you 
for feedfback;by the way,
may be any idea,why,after h.been installed
on a mmc,boots with root partition
mounted ro;
The problem is,if remounted manually rw, wether
wpa_supplicant script nor iwconfig does
connecting
so,no network;-(
Tried one after another 3 postmarketos
builds, no issues thou;don't really like
them because of Wayland,but to day
no other option;
I made partitions,wrote with rsync from
USB stick because dd from image makes for
root partition can. 5gb,again,no fuss there,
if talking about those postmarketos builds,
for example.

I really appreciate your work,also good documented

**Comment by hexdump0815** [comment]
read-only fs usually means data corruption, so maybe badly written image, bad usb device or connection etc.

**Comment by riacht** [comment]
:-)
to day, i failed to get rootfs on /dev/emmc repaired,
fsck,ext4 saying:
"need to have higher version
of e2fsck"  or somthing like that
if booting from usb
Suggestions?

**Comment by hexdump0815** [comment]
rootfs is btrfs for quite a while now - if you install to emmc, then make sure to read https://github.com/hexdump0815/imagebuilder/blob/main/doc/install-to-emmc-on-arm-chromebooks.md carefully

**Comment by riacht** [comment]
read, made as you said, but  "btrfs check" does'nt do it for me
