### ISSUE TITLE
chromebook_kukui: problem: v6.7 or higher, booting pregess is stuck at this line: failed to start systemd-logind.

### ISSUE THREAD

**Issue by krrrak** [hexdump0815/linux-mainline-mediatek-mt81xx-kernel#14]
board: katsu.
using the kconfig config.mt8-6.6.9-stb-mt8+.
As it failed to enter the system, I don't know how to cat the log because I can't use systemctl status.

**Comment by hexdump0815** [comment]
i did not have a look at anything newer than v6.6, so if you want to try newer versions you'll have to debug them yourself right now - for that a suzyqable is very helpful to get a serial console - see: https://github.com/hexdump0815/linux-mainline-on-arm-chromebooks

**Comment by krrrak** [comment]
switch to debian sid has fixed it.
