### ISSUE TITLE
chromebook_kukui: misc: video decoding/encoding fix for kukui

### ISSUE THREAD

**Issue by aneeshlingala** [hexdump0815/linux-mainline-mediatek-mt81xx-kernel#6]
Hello Hexdump0815,

I found some info about a video decoding/encoding fix. Somehow, postmarketOS guys fixed it!

Here is the [kernel patch](https://gitlab.com/postmarketOS/pmaports/-/blob/master/device/testing/linux-postmarketos-mediatek-mt8183/CHROMIUM-ARM64-dts-add-vdec-venc-h264-dtsi.patch). It is for postmarketOS kernel v6.1.28.

Thanks,
Aneesh

**Comment by hexdump0815** [comment]
thanks a lot for the info - the author of the patch was actually also so nice to let me know about it via irc: https://oftc.irclog.whitequark.org/linux-cros-arm/2023-05-18 - i have noted it down already and will include it for my next round of kernel builds in the next weeks ... just still having a little break right now

**Comment by aneeshlingala** [comment]
Nice!

I will be closing the issue.
