### ISSUE TITLE
How to fix Bluetooth on other kernels

### ISSUE THREAD

**Issue by aneeshlingala** [hexdump0815/linux-mainline-mediatek-mt81xx-kernel#8]
I got Arch linux running on my kappa with mainline kernel (linux-aarch64). I downloaded the extra files folder and copied them, that fixed wifi and sound. Now, I would like to contribute to the mainline Arch kernel with a Bluetooth patch for mt8183. If you can write a small document about the patches and how to patch a kernel, that would    be awesome!

Thanks,
Aneesh

**Comment by hexdump0815** [comment]
as you closed the issue i guess you found it out yourself: https://github.com/hexdump0815/linux-mainline-mediatek-mt81xx-kernel/blob/master/misc.cbm/patches/v6.1/mt8183-fix-bluetooth.patch should fix bluetooth - i did not test it for > v6.1 yet, but most probably it should still work ...
